export const LOGIN_USER = "LOGIN_USER";
export const ACTIVE_CODE = "ACTIVE_CODE";

export const CREATE_NEW_PRODUCT = "CREATE_NEW_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const PRINT_PRODUCT = "PRINT_PRODUCT";
export const GET_PRODUCT_CODE = "GET_PRODUCT_CODE";

export const CREATE_NEW_BUY_INVOICE = "CREATE_NEW_BUY_INVOICE";
export const CREATE_NEW_PDF_BUY_INVOICE = "CREATE_NEW_PDF_BUY_INVOICE";
export const GET_ALL_BUY_INVOICES = "GET_ALL_BUY_INVOICES";
export const GET_ONE_BUY_INVOICE = "GET_ONE_BUY_INVOICE";
export const UPDATE_BUY_INVOICE = "UPDATE_BUY_INVOICE";
export const DELETE_BUY_INVOICE = "DELETE_BUY_INVOICE";
export const PRINT_BUY_INVOICE = "PRINT_BUY_INVOICE";

export const CREATE_NEW_SALE_INVOICE = "CREATE_NEW_SALE_INVOICE";

export const GET_ALL_SALE_INVOICES = "GET_ALL_SALE_INVOICES";
export const GET_ONE_SALE_INVOICE = "GET_ONE_SALE_INVOICE";
export const UPDATE_SALE_INVOICE = "UPDATE_SALE_INVOICE";
export const DELETE_SALE_INVOICE = "DELETE_SALE_INVOICE";
export const PRINT_SALE_INVOICE = "PRINT_SALE_INVOICE";
export const PRINT_ONE_SALE_INVOICE = "PRINT_ONE_SALE_INVOICE";

export const CREATE_NEW_STORE = "CREATE_NEW_STORE";
export const GET_ALL_STORES = "GET_ALL_STORES";
export const GET_ONE_STORE = "GET_ONE_STORE";
export const UPDATE_STORE = "UPDATE_STORE";
export const DELETE_STORE = "DELETE_STORE";
export const PRINT_STORE = "PRINT_STORE";

export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ONE_USER = "GET_ONE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";

export const CREATE_NEW_COMPANY = "CREATE_NEW_COMPANY";
export const GET_ALL_COMPANY = "GET_ALL_COMPANY";
export const GET_ONE_COMPANY = "GET_ONE_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const DELETE_COMPANY = "DELETE_COMPANY";
